/* eslint-disable object-shorthand */
/* eslint-disable space-before-function-paren */
/* eslint-disable prefer-arrow-callback */
/* eslint-disable arrow-parens */
/* eslint-disable arrow-body-style */
/* eslint-disable func-names */
/* eslint-disable max-len */
// @ts-nocheck

/* --------------------------------------------------------------- */

/*
Diferencias y Similitudes Entre function() {} Función Regular (Regular Function) y () => {} Función Flecha (Arrow Function)

- Midudev:
https://twitter.com/midudev/status/1658459474749796352

- Jon Mircha:
https://youtu.be/WuCw9agV3Rc

- ESLint Airbnb:
https://airbnb.io/javascript/#arrow-functions

- JavaScript Info:
https://javascript.info/function-expressions

https://javascript.info/arrow-functions-basics

https://javascript.info/arrow-functions

- Documentacion Oficial:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions#arrow_functions

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions#the_arrow_function_expression

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

Las diferencias tienen fondo amarillo: */

//                                                                                                       |-----------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------|
//                                                                                                       | Función Flecha                                                                                      | Función Regular                                                                                       |
//                                                                                                       | (Arrow Function)                                                                                    | (Regular Function)                                                                                    |
// |-----------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------|
// | return implícito:                                                                                   | ✓                                                                                                   | X                                                                                                     |
// | ¿Se puede retornar un valor                                                                         |                                                                                                     |                                                                                                       |
// | SIN escribir return?                                                                                | const sumar = (...rest) => rest.reduce((acumulador, elemento) => acumulador + elemento);            | function sumar (...rest) {                                                                            |
// |                                                                                                     |                                                                                                     |   return rest.reduce((acumulador, elemento) => acumulador + elemento);                                |
// |                                                                                                     | const valorDeRetorno = sumar(1, 2, 3); // 1+2+3 = 6                                                 | }                                                                                                     |
// |                                                                                                     | console.log(valorDeRetorno);                                                                        |                                                                                                       |
// |                                                                                                     | // 6                                                                                                | sumar(1, 2, 3); // 1+2+3 = 6                                                                          |
// |                                                                                                     |                                                                                                     | // 6                                                                                                  |
// |-----------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------|
// | ¿Sirve para crear objetos?                                                                          | X                                                                                                   | ✓                                                                                                     |
// |                                                                                                     |                                                                                                     |                                                                                                       |
// |                                                                                                     | const Persona = (nombre) => { /* ... */ };                                                          | function Persona(nombre) {                                                                            |
// |                                                                                                     | const midu = new Persona('midudev');                                                                |  this.nombre = nombre;                                                                                |
// |                                                                                                     | // ❌ TypeError: persona is not a constructor                                                       |                                                                                                       |
// |                                                                                                     |                                                                                                     |  console.log(this);                                                                                   |
// |                                                                                                     |                                                                                                     |  /*                                                                                                   |
// |                                                                                                     |                                                                                                     |   persona {                                                                                           |
// |                                                                                                     |                                                                                                     |     nombre: 'midudev',                                                                                |
// |                                                                                                     |                                                                                                     |     __proto__: { constructor: ƒ persona() }                                                           |
// |                                                                                                     |                                                                                                     |   }                                                                                                   |
// |                                                                                                     |                                                                                                     |  */                                                                                                   |
// |                                                                                                     |                                                                                                     |  console.log(this.nombre); // 'midudev'                                                               |
// |                                                                                                     |                                                                                                     |  console.log(nombre);      // 'midudev'                                                               |
// |                                                                                                     |                                                                                                     | }                                                                                                     |
// |                                                                                                     |                                                                                                     |                                                                                                       |
// |                                                                                                     |                                                                                                     | const midu = new Persona('midudev');                                                                  |
// |                                                                                                     |                                                                                                     | console.log(midu);                                                                                    |
// |                                                                                                     |                                                                                                     | /*                                                                                                    |
// |                                                                                                     |                                                                                                     | persona {                                                                                             |
// |                                                                                                     |                                                                                                     |    nombre: 'midudev',                                                                                 |
// |                                                                                                     |                                                                                                     |    __proto__: { constructor: ƒ persona() }                                                            |
// |                                                                                                     |                                                                                                     | }                                                                                                     |
// |                                                                                                     |                                                                                                     | */                                                                                                    |
// |                                                                                                     |                                                                                                     |                                                                                                       |
// |                                                                                                     |                                                                                                     | console.log(midu.nombre);                                                                             |
// |                                                                                                     |                                                                                                     | // 'midudev'                                                                                          |
// |-----------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------|
// | ¿Tiene acceso a los                                                                                 | X                                                                                                  | ✓                                                                                                      |
// | argumentos arguments de la funcion?                                                                 |                                                                                                    |                                                                                                        |
// | https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/arguments | const funcionFlecha = (a, b, c) => {                                                               | function funcionRegular (a, b, c) {                                                                    |
// | https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments               |   // ❌ Uncaught ReferenceError: arguments is not defined                                          |   for (let i = 0; i < funcionRegular.length; i++) {                                                    |
// |                                                                                                     |   console.log(arguments);                                                                          |     console.log(arguments[i]);                                                                         |
// |                                                                                                     | };                                                                                                 |     /*                                                                                                 |
// |                                                                                                     |                                                                                                    |     'uno'                                                                                              |
// |                                                                                                     | funcionFlecha('uno', 'dos', 'tres');                                                               |     'dos'                                                                                              |
// |                                                                                                     |                                                                                                    |     'tres'                                                                                             |
// |                                                                                                     |                                                                                                    |     */                                                                                                 |
// |                                                                                                     |                                                                                                    |   }                                                                                                    |
// |                                                                                                     |                                                                                                    |                                                                                                        |
// |                                                                                                     |                                                                                                    |   console.log(arguments);                                                                              |
// |                                                                                                     |                                                                                                    |   /*                                                                                                   |
// |                                                                                                     |                                                                                                    |     {                                                                                                  |
// |                                                                                                     |                                                                                                    |       '0': 'uno',                                                                                      |
// |                                                                                                     |                                                                                                    |       '1': 'dos',                                                                                      |
// |                                                                                                     |                                                                                                    |       '2': 'tres',                                                                                     |
// |                                                                                                     |                                                                                                    |       length: 3,                                                                                       |
// |                                                                                                     |                                                                                                    |       callee: ƒ funcionRegular(),                                                                      |
// |                                                                                                     |                                                                                                    |       __proto__: {                                                                                     |
// |                                                                                                     |                                                                                                    |         constructor: ƒ Object(),                                                                       |
// |                                                                                                     |                                                                                                    |         __defineGetter__: ƒ __defineGetter__(),                                                        |
// |                                                                                                     |                                                                                                    |         __defineSetter__: ƒ __defineSetter__(),                                                        |
// |                                                                                                     |                                                                                                    |         hasOwnProperty: ƒ hasOwnProperty(),                                                            |
// |                                                                                                     |                                                                                                    |         __lookupGetter__: ƒ __lookupGetter__(),                                                        |
// |                                                                                                     |                                                                                                    |         __lookupSetter__: ƒ __lookupSetter__(),                                                        |
// |                                                                                                     |                                                                                                    |         isPrototypeOf: ƒ isPrototypeOf(),                                                              |
// |                                                                                                     |                                                                                                    |         propertyIsEnumerable: ƒ propertyIsEnumerable(),                                                |
// |                                                                                                     |                                                                                                    |         toString: ƒ toString(),                                                                        |
// |                                                                                                     |                                                                                                    |         valueOf: ƒ valueOf(),                                                                          |
// |                                                                                                     |                                                                                                    |         toLocaleString: ƒ toLocaleString()                                                             |
// |                                                                                                     |                                                                                                    |       }                                                                                                |
// |                                                                                                     |                                                                                                    |     }                                                                                                  |
// |                                                                                                     |                                                                                                    |   */                                                                                                   |
// |                                                                                                     |                                                                                                    | }                                                                                                      |
// |                                                                                                     |                                                                                                    |                                                                                                        |
// |                                                                                                     |                                                                                                    | funcionRegular('uno', 'dos', 'tres');                                                                  |
// |-----------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------|
// | ¿Captura el objeto this del contexto en que se encuentra?                                           | X                                                                                                  | ✓                                                                                                      |
// | https://youtu.be/byirHCoSPFY                                                                        | La funcion flecha NO enlaza el valor de this                                                       |                                                                                                        |
// | https://eslint.org/docs/latest/rules/object-shorthand                                               | y por lo tanto será el valor heredado en el scope                                                  |                                                                                                        |
// |                                                                                                     |----------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------|
// |                                                                                                     |                                                                            const objetoLiteral = {                                                                                                          |
// |                                                                                                     |                                                                              nombre: 'midu',                                                                                                                |
// |                                                                                                     |                                                                                                                                                                                                             |
// |                                                                                                     |                                                                              funcionRegular1: function() {                                                                                                  |
// |                                                                                                     |                                                                                console.log(`Hola ${this.nombre}`); // 'Hola midu'                                                                           |
// |                                                                                                     |                                                                             },                                                                                                                              |
// |                                                                                                     |                                                                             funcionRegular2() {                                                                                                             |
// |                                                                                                     |                                                                               console.log(`Hola ${this.nombre}`); // 'Hola midu'                                                                            |
// |                                                                                                     |                                                                             },                                                                                                                              |
// |                                                                                                     |                                                                                                                                                                                                             |
// |                                                                                                     |                                                                             funcionFlecha: () => {                                                                                                          |
// |                                                                                                     |                                                                               console.log(`Hola ${this.nombre}`); // 'Hola undefined'                                                                       |
// |                                                                                                     |                                                                             }                                                                                                                               |
// |                                                                                                     |                                                                            }                                                                                                                                |
// |                                                                                                     |                                                                            console.log(objetoLiteral);                                                                                                      |
// |                                                                                                     |                                                                            /*                                                                                                                               |
// |                                                                                                     |                                                                             {                                                                                                                               |
// |                                                                                                     |                                                                               nombre: 'midu',                                                                                                               |
// |                                                                                                     |                                                                               funcionRegular1: ƒ funcionRegular1(),                                                                                         |
// |                                                                                                     |                                                                               funcionRegular2: ƒ funcionRegular2(),                                                                                         |
// |                                                                                                     |                                                                               funcionFlecha: ƒ funcionFlecha()                                                                                              |
// |                                                                                                     |                                                                             }                                                                                                                               |
// |                                                                                                     |                                                                            */                                                                                                                               |
// |                                                                                                     |                                                                                                                                                                                                             |
// |                                                                                                     |                                                                            objetoLiteral.funcionRegular1(); // 'Hola midu'                                                                                  |
// |                                                                                                     |                                                                            objetoLiteral.funcionRegular2(); // 'Hola midu'                                                                                  |
// |                                                                                                     |                                                                                                                                                                                                             |
// |                                                                                                     |                                                                            objetoLiteral.funcionFlecha();   // 'Hola undefined'                                                                             |
// |-----------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------|
// | ¿Sirve con la palabra reservada super?                                                              | X                                                                                                   | ✓                                                                                                     |
// | super permite que la clase hija acceda a los metodos y propiedades de la clase padre                |                                                                                                     |                                                                                                       |
// | https://javascript.info/class-inheritance                                                           | class ClasePadre {                                                                                  | class ClasePadre {                                                                                    |
// | https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/super                   |  funcionFlecha = () => {                                                                            |  funcionRegular() {                                                                                   |
// |                                                                                                     |    console.log('hola mundo');                                                                       |    console.log('hola mundo');                                                                         |
// |                                                                                                     |  };                                                                                                 |  }                                                                                                    |
// |                                                                                                     | }                                                                                                   | }                                                                                                     |
// |                                                                                                     |                                                                                                     |                                                                                                       |
// |                                                                                                     | class ClaseHija extends ClasePadre {                                                                | class ClaseHija extends ClasePadre {                                                                  |
// |                                                                                                     |   bar() {                                                                                           |   bar() {                                                                                             |
// |                                                                                                     |    /* Sólo se puede acceder                                                                         |     super.funcionRegular();                                                                           |
// |                                                                                                     |    a los métodos públicos y protegidos                                                              |   }                                                                                                   |
// |                                                                                                     |    de la clase base mediante la palabra clave 'super' */                                            | }                                                                                                     |
// |                                                                                                     |    super.funcionFlecha();                                                                           |                                                                                                       |
// |                                                                                                     |   }                                                                                                 | const instanciaHija = new ClaseHija();                                                                |
// |                                                                                                     | }                                                                                                   | instanciaHija.bar();                                                                                  |
// |                                                                                                     |                                                                                                     | // 'hola mundo'                                                                                       |
// |                                                                                                     | const instanciaHija = new ClaseHija();                                                              |                                                                                                       |
// |                                                                                                     | instanciaHija.bar();                                                                                |                                                                                                       |
// |                                                                                                     | // ❌ Uncaught TypeError: (intermediate value).funcionFlecha is not a function at ClaseHija.bar     |                                                                                                       |
// |-----------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------|
// | ¿Sirve con el constructor new?                                                                      | X                                                                                                   | ✓                                                                                                     |
// | https://dev.to/bhagatparwinder/arrow-function-and-the-new-arguments-super-keyword-2d1l              |                                                                                                     |                                                                                                       |
// | https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new                     | const FuncionFlecha = () => { /* ... */ };                                                          | function FuncionRegular () { /* ... */ }                                                              |
// |                                                                                                     | const bar = new FuncionFlecha();                                                                    | const bar = new FuncionRegular();                                                                     |
// |                                                                                                     | // ❌ TypeError: funcionFlecha is not a constructor                                                 | console.log(bar);                                                                                     |
// |                                                                                                     |                                                                                                     | /*                                                                                                    |
// |                                                                                                     |                                                                                                     |   funcionRegular {                                                                                    |
// |                                                                                                     |                                                                                                     |      __proto__: { constructor: ƒ funcionRegular() }                                                   |
// |                                                                                                     |                                                                                                     |   }                                                                                                   |
// |                                                                                                     |                                                                                                     | */                                                                                                    |
// |-----------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------|
// | ¿Sirve con la propiedad prototype?                                                                  | X                                                                                                   | ✓                                                                                                     |
// | https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/prototype |                                                                                                     |                                                                                                       |
// |                                                                                                     | const funcionFlecha = () => { /* ... */ };                                                          | // Definir función constructora llamada "Persona"                                                     |
// |                                                                                                     | console.log(funcionFlecha.prototype);                                                               | function Persona(nombre, edad) {                                                                      |
// |                                                                                                     | // undefined                                                                                        |  this.nombre = nombre;                                                                                |
// |                                                                                                     |                                                                                                     |  console.log(nombre);      // 'Juan'                                                                  |
// |                                                                                                     |                                                                                                     |  console.log(this.nombre); // 'Juan'                                                                  |
// |                                                                                                     |                                                                                                     |                                                                                                       |
// |                                                                                                     |                                                                                                     |  this.edad = edad;                                                                                    |
// |                                                                                                     |                                                                                                     |  console.log(edad);      // 30                                                                        |
// |                                                                                                     |                                                                                                     |  console.log(this.edad); // 30                                                                        |
// |                                                                                                     |                                                                                                     | }                                                                                                     |
// |                                                                                                     |                                                                                                     |                                                                                                       |
// |                                                                                                     |                                                                                                     | // Definir método en el prototipo de la función Persona                                               |
// |                                                                                                     |                                                                                                     | Persona.prototype.saludar = function() {                                                              |
// |                                                                                                     |                                                                                                     |   return `Hola, soy ${this.nombre} y tengo ${this.edad} años.`;                                       |
// |                                                                                                     |                                                                                                     | };                                                                                                    |
// |                                                                                                     |                                                                                                     |                                                                                                       |
// |                                                                                                     |                                                                                                     | // Crear una instancia de Persona                                                                     |
// |                                                                                                     |                                                                                                     | const persona1 = new Persona('Juan', 30);                                                             |
// |                                                                                                     |                                                                                                     |                                                                                                       |
// |                                                                                                     |                                                                                                     | // Llamar al método saludar en la instancia                                                           |
// |                                                                                                     |                                                                                                     | persona1.saludar();                                                                                   |
// |                                                                                                     |                                                                                                     | // "Hola, soy Juan y tengo 30 años."                                                                  |
// |-----------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------|
// | Elevacion (hoisting) (MALA PRACTICA):                                                               | X                                                                                                   | ✓                                                                                                     |
// | ¿La funcion se puede ejecutar ANTES de inicializarse?                                               |                                                                                                     |                                                                                                       |
// |                                                                                                     | funcionFlecha();                          // ejecutar funcion                                       | declaracionDeFuncion();                                                                               |
// | Recordatorio:                                                                                       |                                                                                                     | // 'hola mundo'                                                                                       |
// | Ver:                                                                                                | const funcionFlecha = () => 'hola mundo'; // inicializar funcion                                    |                                                                                                       |
// | " 4.2.3.2) Elevación de Declaración de Función "                                                    | // ❌ Uncaught ReferenceError: funcionFlecha is not defined                                         | function declaracionDeFuncion () {                                                                    |
// |                                                                                                     |                                                                                                     |    return 'hola mundo';                                                                               |
// |                                                                                                     |                                                                                                     | }                                                                                                     |
// |-----------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------|
// | Sintaxis en metodos de [] array:                                                                    | const letras = ['A', 'B', 'C'];                                                                     | // Palabra reservada function                                                                         |
// | .map() .filter() .reduce() .toSorted(), etc.                                                        | console.log(letras);                                                                                | letras.forEach(function (elemento, i) { // MALA PRACTICA                                              |
// | https://eslint.org/docs/latest/rules/prefer-arrow-callback                                          | // (3) [ 'A', 'B', 'C' ]                                                                            |   console.log(`i=${i} ➜ elemento='${elemento}'`);                                                     |
// | https://airbnb.io/javascript/#arrow-functions                                                       |                                                                                                     | });                                                                                                   |
// |                                                                                                     | // Funcion flecha (arrow function)                                                                  | /*                                                                                                    |
// |                                                                                                     | letras.forEach((elemento, i) => { // BUENA PRACTICA                                                 |  "i=0 ➜ elemento='A'"                                                                                |
// |                                                                                                     |  console.log(`i=${i} ➜ elemento='${elemento}'`);                                                    | "i=1 ➜ elemento='B'"                                                                                |
// |                                                                                                     | });                                                                                                 |  "i=2 ➜ elemento='C'"                                                                                |
// |                                                                                                     | /*                                                                                                  | */                                                                                                    |
// |                                                                                                     | "i=0 ➜ elemento='A'"                                                                                |                                                                                                      |
// |                                                                                                     | "i=1 ➜ elemento='B'"                                                                                |                                                                                                      |
// |                                                                                                     | "i=2 ➜ elemento='C'"                                                                                |                                                                                                      |
// |                                                                                                     | */                                                                                                  |                                                                                                      |
// |                                                                                                     |                                                                                                     |                                                                                                      |
// |                                                                                                     | // Funcion flecha en una sola linea (inline arrow function)                                         |                                                                                                      |
// |                                                                                                     | letras.forEach((elemento, i) => console.log(`i=${i} ➜ elemento='${elemento}'`)); // BUENA PRACTICA  |                                                                                                      |
// |                                                                                                     | /*                                                                                                  |                                                                                                      |
// |                                                                                                     | "i=0 ➜ elemento='A'"                                                                                |                                                                                                      |
// |                                                                                                     | "i=1 ➜ elemento='B'"                                                                                |                                                                                                      |
// |                                                                                                     | "i=2 ➜ elemento='C'"                                                                                |                                                                                                      |
// |                                                                                                     | */                                                                                                  |                                                                                                       |
// |-----------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------|
// | ¿Sirve con async await?                                                                             | ✓                                                                                                   | ✓                                                                                                     |
// |                                                                                                     |                                                                                                     |                                                                                                       |
// |                                                                                                     | const funcionFlecha = async () => {                                                                 | async function funcionRegular () {                                                                    |
// |                                                                                                     |  try {                                                                                              |  try {                                                                                                |
// |                                                                                                     |    const url = 'https://jsonplaceholder.typicode.com/todos/1';                                      |    const url = 'https://jsonplaceholder.typicode.com/todos/1';                                        |
// |                                                                                                     |    const response = await fetch(url);                                                               |    const response = await fetch(url);                                                                 |
// |                                                                                                     |                                                                                                     |                                                                                                       |
// |                                                                                                     |    const data = await response.json();                                                              |    const data = await response.json();                                                                |
// |                                                                                                     |    console.log(data);                                                                               |    console.log(data);                                                                                 |
// |                                                                                                     |  } catch (error) {                                                                                  |  } catch (error) {                                                                                    |
// |                                                                                                     |    console.error(`error en fetch ➜ ${error}`);                                                     |    console.error(`error en fetch ➜ ${error}`);                                                        |
// |                                                                                                     |  }                                                                                                  |  }                                                                                                    |
// |                                                                                                     | }                                                                                                   | }                                                                                                     |
// |                                                                                                     |                                                                                                     |                                                                                                       |
// |                                                                                                     | funcionFlecha();                                                                                    | funcionRegular();                                                                                     |
// |                                                                                                     | /*                                                                                                  | /*                                                                                                    |
// |                                                                                                     |   Promise {<pending>}                                                                               | Promise { <pending> }                                                                                 |
// |                                                                                                     |                                                                                                     |                                                                                                       |
// |                                                                                                     |  {                                                                                                  | {                                                                                                     |
// |                                                                                                     |   userId: 1,                                                                                        |   userId: 1,                                                                                          |
// |                                                                                                     |   id: 1,                                                                                            |   id: 1,                                                                                              |
// |                                                                                                     |   title: 'delectus aut autem',                                                                      |   title: 'delectus aut autem',                                                                        |
// |                                                                                                     |   completed: false                                                                                  |   completed: false                                                                                    |
// |                                                                                                     |  }                                                                                                  | }                                                                                                     |
// |                                                                                                     | */                                                                                                  | */                                                                                                    |
// |-----------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------|
// | Sintaxis                                                                                            | https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#syntax  | Declaración de función:                                                                               |
// |                                                                                                     |                                                                                                     | https://developer.mozilla.org/es/docs/Web/JavaScript/Guide/Functions#declaraci%C3%B3n_de_funci%C3%B3n |
// |                                                                                                     | () => expression                                                                                    |                                                                                                       |
// |                                                                                                     |                                                                                                     | function nombreFuncion (param1, paramN) {                                                             |
// |                                                                                                     | param => expression                                                                                 |    // statements                                                                                      |
// |                                                                                                     |                                                                                                     |                                                                                                       |
// |                                                                                                     | (param) => expression                                                                               |    return valorDeRetorno                                                                              |
// |                                                                                                     |                                                                                                     | }                                                                                                     |
// |                                                                                                     | (param1, paramN) => expression                                                                      |                                                                                                       |
// |                                                                                                     |                                                                                                     |                                                                                                       |
// |                                                                                                     | () => {                                                                                             |                                                                                                       |
// |                                                                                                     |   // statements                                                                                     |                                                                                                       |
// |                                                                                                     | }                                                                                                   |                                                                                                       |
// |                                                                                                     |                                                                                                     |                                                                                                       |
// |                                                                                                     | param => {                                                                                          |                                                                                                       |
// |                                                                                                     |  // statements                                                                                      |                                                                                                       |
// |                                                                                                     | }                                                                                                   |                                                                                                       |
// |                                                                                                     |                                                                                                     |                                                                                                       |
// |                                                                                                     | (param1, paramN) => {                                                                               |                                                                                                       |
// |                                                                                                     |  // statements                                                                                      |                                                                                                       |
// |                                                                                                     | }                                                                                                   |                                                                                                       |
// |-----------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------|

/* --------------------------------------------------------------- */

/* Ejemplo 1:
La expresion de funcion se escribe similar a la funcion flecha pero SIN la palabra reservada function
https://youtu.be/WuCw9agV3Rc */

const expresionDeFuncion = function (nombre) {
  return `hola ${nombre}`;
};
const valorRetorno = expresionDeFuncion('Daniel');
console.log(valorRetorno);
// 'hola daniel'

// Funcion flecha CON parametros
const arrowFunction = (nombre) => {
  return `hola ${nombre}`;
};
const valorRetorno2 = arrowFunction('Daniel');
console.log(valorRetorno2);
// 'hola Daniel'

// Funcion flecha SIN parametros
const arrowFunction2 = () => {
  console.log('hola mundo');
};
arrowFunction2();
// 'hola mundo'

/* --------------------------------------------------------------- */

/* Ejemplo 2 - Funcion Flecha en una Sola Linea (Inline Arrow Function)
Cuando dentro del par de llaves {} (scope) de la funcion flecha hay una sola linea de codigo,
entonces se puede escribir en una sola linea SIN la palabra reservada return
https://eslint.org/docs/latest/rules/arrow-body-style

https://youtu.be/WuCw9agV3Rc */

// Funcion flecha en una sola linea CON parametros
const inlineArrowFunction = (nombre) => `hola ${nombre}`;

const valorRetorno3 = inlineArrowFunction('Daniel');
console.log(valorRetorno3);
// 'hola Daniel'

// Funcion flecha en una sola linea SIN parametros
const inlineArrowFunction2 = () => 'hola mundo';
const valorRetorno4 = inlineArrowFunction2();
console.log(valorRetorno4);
// 'hola mundo'

/* --------------------------------------------------------------- */

/* Ejemplo 3:
Cuando hay UN SOLO parametro
la funcion flecha se puede escribir
con o sin parentesis ()
aunque esto segun ESLint Airbnb es MALA PRACTICA
https://eslint.org/docs/latest/rules/arrow-parens

https://youtu.be/WuCw9agV3Rc */

const arrowFunction3 = nombre => { // parametro nombre
  return `hola ${nombre}`;
};
console.log(
  arrowFunction3('Daniel'),
);
// 'hola Daniel'

const inlineArrowFunction3 = nombre => `hola ${nombre}`;
console.log(
  inlineArrowFunction3('Daniel'),
);
// 'hola Daniel'

/* --------------------------------------------------------------- */

/* Ejemplo 4:
https://youtu.be/WuCw9agV3Rc */

const funcionFlechaDeVariasLineas = () => {
  console.log(1);
  console.log(2);
  console.log(3);
};

funcionFlechaDeVariasLineas();
/*
1
2
3
*/

/* --------------------------------------------------------------- */

/* Ejemplo 5:
https://youtu.be/WuCw9agV3Rc */

function thisFuncionRegular() {
  console.log(this);
}
thisFuncionRegular();
// Window {window: Window, self: Window, document: document, name: '', location: Location, ...}

const thisFuncionFlecha = () => {
  console.log(this);
};
thisFuncionFlecha();
// Window {window: Window, self: Window, document: document, name: '', location: Location, ...}
